// manga.dart
import 'package:json_annotation/json_annotation.dart';
part 'mangaSearch.g.dart';

@JsonSerializable(explicitToJson: true)
class Manga {
  final String result;
  final String response;
  final List<Data> data;

  Manga(this.result, this.response, this.data);

  factory Manga.fromJson(Map<String, dynamic> json) => _$MangaFromJson(json);

  Map<String, dynamic> toJson() => _$MangaToJson(this);
}

@JsonSerializable()
class Data {
  final String id;
  final String type;
  final Attributes attributes;
  final List<Relationships> relationships;

  Data(this.id, this.type, this.attributes, this.relationships);

  factory Data.fromJson(Map<String, dynamic> json) => _$DataFromJson(json);
  Map<String, dynamic> toJson() => _$DataToJson(this);
}

@JsonSerializable()
class Attributes {
  final Title title;
  final List<String> altTitles;
  final String description;
  final bool isLocked;
  final Links links;
  final String originalLanguage;
  final String lastVolume;
  final String lastChapter;
  final String publicationDemographic;
  final String status;
  final int year;
  final String contentRating;
  final List<Tags> tags;
  final String state;
  final bool chapterNumbersResetOnNewVolume;
  final String createdAt;
  final String updatedAt;
  final int version;
  final List<String> availableTranslatedLanguages;
  final String latestUploadedChapter;

  Attributes(
      this.title,
      this.altTitles,
      this.description,
      this.isLocked,
      this.links,
      this.originalLanguage,
      this.lastVolume,
      this.lastChapter,
      this.publicationDemographic,
      this.status,
      this.year,
      this.contentRating,
      this.tags,
      this.state,
      this.chapterNumbersResetOnNewVolume,
      this.createdAt,
      this.updatedAt,
      this.version,
      this.availableTranslatedLanguages,
      this.latestUploadedChapter);

  factory Attributes.fromJson(Map<String, dynamic> json) =>
      _$AttributesFromJson(json);
  Map<String, dynamic> toJson() => _$AttributesToJson(this);
}

@JsonSerializable()
class Title {
  final String en;

  Title(this.en);

  factory Title.fromJson(Map<String, dynamic> json) => _$TitleFromJson(json);
  Map<String, dynamic> toJson() => _$TitleToJson(this);
}

@JsonSerializable()
class Links {
  final String al;
  final String ap;
  final String bw;
  final String kt;
  final String mu;
  final String nu;
  final String amz;
  final String cdj;
  final String ebj;
  final String mal;
  final String raw;
  final String engtl;

  Links(this.al, this.ap, this.bw, this.kt, this.mu, this.nu, this.amz,
      this.cdj, this.ebj, this.mal, this.raw, this.engtl);

  factory Links.fromJson(Map<String, dynamic> json) => _$LinksFromJson(json);
  Map<String, dynamic> toJson() => _$LinksToJson(this);
}

@JsonSerializable()
class Tags {
  final String id;
  final String type;
  final Attributes attributes;
  final List<Relationships> relationships;

  Tags(this.id, this.type, this.attributes, this.relationships);

  factory Tags.fromJson(Map<String, dynamic> json) => _$TagsFromJson(json);
  Map<String, dynamic> toJson() => _$TagsToJson(this);
}

@JsonSerializable()
class Relationships {
  final String id;
  final String type;

  Relationships(this.id, this.type);

  factory Relationships.fromJson(Map<String, dynamic> json) =>
      _$RelationshipsFromJson(json);
  Map<String, dynamic> toJson() => _$RelationshipsToJson(this);
}

// This part will be generated by build_runner
